### ISSUE TITLE
Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False

### ISSUE THREAD

**Issue by igormis** [explosion/spacy-pytorch-transformers#33]
The code works on colab and it creates the model, but when I try to load the model on cpu machine with the code
```python
import spacy
test_text = "Searches in Germany; Britain focus on Islamist suspects - prosecutor"
nlp2 = spacy.load('results_sent')
doc2 = nlp2(test_text)
print(test_text, doc2.cats)
```

The following error appears:
```
Traceback (most recent call last):
  File "predict.py", line 4, in <module>
    nlp2 = spacy.load('results_sent')
  File "/home/igor/anaconda3/envs/spacy-torch/lib/python3.6/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/igor/anaconda3/envs/spacy-torch/lib/python3.6/site-packages/spacy/util.py", line 136, in load_model
    return load_model_from_path(Path(name), **overrides)
  File "/home/igor/anaconda3/envs/spacy-torch/lib/python3.6/site-packages/spacy/util.py", line 179, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/igor/anaconda3/envs/spacy-torch/lib/python3.6/site-packages/spacy/language.py", line 836, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/igor/anaconda3/envs/spacy-torch/lib/python3.6/site-packages/spacy/util.py", line 636, in from_disk
    reader(path / key)
  File "/home/igor/anaconda3/envs/spacy-torch/lib/python3.6/site-packages/spacy/language.py", line 831, in <lambda>
    p, exclude=["vocab"]
  File "pipes.pyx", line 222, in spacy.pipeline.pipes.Pipe.from_disk
  File "/home/igor/anaconda3/envs/spacy-torch/lib/python3.6/site-packages/spacy/util.py", line 636, in from_disk
    reader(path / key)
  File "pipes.pyx", line 213, in spacy.pipeline.pipes.Pipe.from_disk.load_model
  File "/home/igor/anaconda3/envs/spacy-torch/lib/python3.6/site-packages/thinc/neural/_classes/model.py", line 362, in from_bytes
    layer.from_bytes(weights[i])
  File "/home/igor/anaconda3/envs/spacy-torch/lib/python3.6/site-packages/thinc/extra/wrappers.py", line 190, in from_bytes
    self._model.load_state_dict(torch.load(filelike))
  File "/home/igor/anaconda3/envs/spacy-torch/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/igor/anaconda3/envs/spacy-torch/lib/python3.6/site-packages/torch/serialization.py", line 573, in _load
    result = unpickler.load()
  File "/home/igor/anaconda3/envs/spacy-torch/lib/python3.6/site-packages/torch/serialization.py", line 536, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/igor/anaconda3/envs/spacy-torch/lib/python3.6/site-packages/torch/serialization.py", line 119, in default_restore_location
    result = fn(storage, location)
  File "/home/igor/anaconda3/envs/spacy-torch/lib/python3.6/site-packages/torch/serialization.py", line 95, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/igor/anaconda3/envs/spacy-torch/lib/python3.6/site-packages/torch/serialization.py", line 79, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

**Comment by igormis** [comment]
I have changed the file
python3.6/site-packages/thinc/extra/wrappers.py

**Comment by honnibal** [comment]
Thanks, I guess I got some PyTorch semantics wrong. I'm not sure I understand how it's supposed to work.

So when you serialize the model, PyTorch records which device it was on?? I can't understand how that makes sense. Surely PyTorch should just be loading it into the current active device?

**Comment by igormis** [comment]
In my opinion, this parameter (map_location=torch.device('cpu')) should be transferred from the main function.

**Comment by honnibal** [comment]
Hmm. PyTorch indeed records whether the model was on GPU or CPU in the state dict, and then you have to overrule that when you load it back in. To me this is quite a regrettable design: https://pytorch.org/tutorials/beginner/saving_loading_models.html

I think we should rather make this consistent with the way Thinc and spaCy work. I'll change it to get the current active device of the wrapper, and use that to calculate the right PyTorch `map_location` argument.

If we load the model onto a different device than Thinc and spaCy expect, it won't work anyway for other reasons -- so I don't see much advantage in asking the user to pass through this config.

**Comment by igormis** [comment]
Your solution seems obvious. Thanks.

**Comment by honnibal** [comment]
No problem, thanks for the report. I'll keep this open until the fix is implemented.

**Comment by Sai2421** [comment]
something similar happened with me while using pickle to deserialize a neural net model, what i did is before serializing it into ".pkl" file, I moved the model to cpu using "model.to("cpu") in my jupyter notebook and then serialized it. Try using the same with issue, not sure but hope it works. Worked for me.
